### ISSUE TITLE
Add support for containerization

### ISSUE THREAD

**Issue by zleyyij** [r-Techsupport/rts-cms#13]
End result should mount `./cms-data` from the outside, and support the OCI container spec (Docker/Podman)
https://discord.com/channels/749314018837135390/1240828670986162247/1247725710408421387

**Comment by PipeItToDevNull** [comment]
This i based off alpine, the resulting image is 23.7MB.

Example basic usage
```bash
cp default.env .env
podman build -t rts-cms .   
podman run --rm -d -v ~/git/rts-cms/:/app/cms-data/ -p 8080:8080 rts-cms
```

I cannot confirm the webserver is reachable on my mac for some reason

**Comment by PipeItToDevNull** [comment]
I tested this on RHEL and it works, so this can be merged 
<img width="1287" alt="image" src="https://github.com/r-Techsupport/rts-cms/assets/25917750/e877ee6b-ab55-4228-a8bc-c4b75b10acf4">
